### ISSUE TITLE
How to install the provided "WineTahomaBit" font under linux?

### ISSUE THREAD

**Issue by xray-tango** [ungstein/OG-Steam#29]
I have been trying to get it to work for 3 hours now at this point.

**Comment by ungstein** [comment]
Sorry, I haven't tested the font in Linux.

**Comment by xray-tango** [comment]
I gotta stick with Times New Roman then...

**Comment by mutageneral** [comment]
FON files are .EXE files that have been renamed to use the .fon extension. Instead of containing an executable program, a FON file contains bitmapped or stroked fonts saved as FNT files. Notably, the fonts contained within a FON file cannot be resized like TrueType (.TTF) fonts. So, you find several similar yet differently-sized fonts within a FON file. 

What you can try is to convert it to a more modern format:
https://askubuntu.com/questions/205969/how-do-i-port-a-fon-font-to-a-linux-font

Here is my try of converting the font: https://ufile.io/wuo4mtcl
